### ISSUE TITLE
ERROR TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dirtdiver9** [hacklanta/hubot-yardmaster#15]
Hubot is reporting an error when running some commands but not all.

hubot show last build for <JOB>

[Thu Sep 03 2015 17:19:10 GMT-0700 (PDT)] ERROR TypeError: Cannot read property 'replace' of undefined
  at /home/jenkins-slave/jarvis/node_modules/hubot-yardmaster/src/yardmaster.coffee:214:17, <js>:227:38
  at /home/jenkins-slave/jarvis/node_modules/hubot-yardmaster/src/yardmaster.coffee:67:9, <js>:37:16
  at IncomingMessage.<anonymous> (/home/jenkins-slave/jarvis/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

**Comment by riveramj** [comment]
The format of the `id` updated in the jenkins api. this has been fixed :-D
